version: "3.8"

services:
  app:
    build: .
    container_name: symfony_app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=dev
    command: ["php", "-S", "0.0.0.0:8000", "-t", "public"]